### ISSUE TITLE
HW 7 th lesson - deadline 26.06.2022 at 17.00

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#10]
Решили перенести дедлайн на воскресенье
Тут ещё один приер коллекции https://www.getpostman.com/collections/e4f771fbf7dc5bed1a52

https://testbase.atlassian.net/wiki/home (логин — mail.for.testbase@gmail.com; пароль — 123456789) тут лежит документация по апишке и описание методов 
Ваше ДЗ:
1.  Сделать запросы createuser, doregister  and delete avatar в формате удобном вам
2. Попытаться протестировать эти методы, пользуясь входными данными из этого документа, прибегая к анализу и различным техникам тест-дизайна. (Проверок делаете, сколько считаете нужным) Например, попробовать отправить запрос без параметра, обязательного для заполнения. Кто чувствует в себе силы и мощь, может тесты автоматизировать 
3. Не более 5 проверок из пункта 2 оформить в отдельном документе со скриншотами и пояснениями, что именно проверяли.
4. А также поделиться коллекциями ваших запросов. Не забываем их сохранять после работы.

ссылка на коллекцию, что мы делали после урока: https://www.getpostman.com/collections/b14947e942accfcd33af

[Практикум(7).pdf](https://github.com/helga-spivak/3008/files/8943257/7.pdf)

**Comment by Polinkarnilova** [comment]
https://www.getpostman.com/collections/adf9b92f65d9c1e2a7e5 



[Karnilova "Postman".xlsx](https://github.com/helga-spivak/3008/files/8984563/Karnilova.Postman.xlsx)

**Comment by viktoria1807** [comment]
[HW 7.Vika.xlsx](https://github.com/helga-spivak/3008/files/8984838/HW.7.Vika.xlsx)

https://www.getpostman.com/collections/bc6f62a9701f43df3bab

**Comment by AntonMatra** [comment]
https://www.getpostman.com/collections/7a85a4e5b8f10ef87545
[HW7 Matruhovich.docx](https://github.com/helga-spivak/3008/files/8984995/HW7.Matruhovich.docx)

**Comment by Avaellru** [comment]
https://www.getpostman.com/collections/601af90b59761d216349
[RudskiHW7.docx](https://github.com/helga-spivak/3008/files/8985014/RudskiHW7.docx)

**Comment by darya-zhuravskaya** [comment]
[HW 7](https://docs.google.com/document/d/1UOGmITM5k6XK-ivjQ3unjtJlg0MtDmo5rGe2vxFIoPc/edit?usp=sharing)
[Collection](https://www.getpostman.com/collections/b20cb50eb3a30b2d4754) - import as a link
[Environment](https://drive.google.com/file/d/1EiUbCEHcmomHVJcSRg5LP83AVnPVZYso/view?usp=sharing) - download and import as a file

**Comment by JuliVoitovich** [comment]
[дз7.xlsx](https://github.com/helga-spivak/3008/files/8985628/7.xlsx)
https://www.getpostman.com/collections/dc7d5a5f00f0683e5048

**Comment by ZhNi5** [comment]
Zhiznevskaya

https://www.getpostman.com/collections/8dd9f4dcc2270191e140
[h_w7.xls](https://github.com/helga-spivak/3008/files/8986243/h_w7.xls)

**Comment by ciaonastya** [comment]
https://www.getpostman.com/collections/ba6957ee9f2b13068336

https://docs.google.com/spreadsheets/d/17PIZ7_kSWcYVyP6CcapA7QC7d8KhByVPWvRMi31Qwu0/export?format=xlsx&id=17PIZ7_kSWcYVyP6CcapA7QC7d8KhByVPWvRMi31Qwu0

**Comment by MariaDanchenko** [comment]
https://www.getpostman.com/collections/0a0e2b42c2ed3c484724


[Маша.xlsx](https://github.com/helga-spivak/3008/files/8986714/default.xlsx)

**Comment by elenaastreika** [comment]
[HW7.xlsx](https://github.com/helga-spivak/3008/files/8986734/HW7.xlsx)

https://www.getpostman.com/collections/dec8d282aa5dd84e8c8d

**Comment by PapaKaertoshka** [comment]
Seva
https://www.getpostman.com/collections/bf64309bc3c689425294

**Comment by skalenchits** [comment]
https://www.getpostman.com/collections/1109507e4c97d799df1f


[запросы.xlsx](https://github.com/helga-spivak/3008/files/8986907/default.xlsx)

**Comment by helga-spivak** [comment]
Deadline
