### ISSUE TITLE
HW 8 lessons 3- deadline 27.06.2022 at 17.00

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#11]
Вашей домашкой бдет сделать задачи: 10, 11, 12, 13, 16* ( она сложная, но кому интересно, может пробовать), 17, 18, 19, 21, 22 (https://www.sql-ex.ru/) - мне скринуть скрины (оформить в один документ) такого плана (видно номер задачи, ваш код и что запрос верный)

![Image](https://user-images.githubusercontent.com/57717954/175380117-638af71e-d3e3-4fac-96df-b44e8b70001a.png)

https://www.w3schools.com/sql/default.asp - тут почитать и выучить все что проходили на уроке:

1. SQL SELECT DISTINCT,
2. SQL WHERE
3. SQL AND, OR and NOT Operators
4. SQL ORDER BY
5. SQL INSERT INTO
6. SQL UPDATE 
7. SQL DELETE
8. SQL TOP, LIMIT, FETCH FIRST or ROWNUM
9. SQL MIN() and MAX()
10. SQL COUNT(), AVG() and SUM()
11. SQL LIKE
12. SQL IN
13. SQL BETWEEN
14. SQL INNER JOIN

**Comment by darya-zhuravskaya** [comment]
[Homework8](https://docs.google.com/spreadsheets/d/1ZLPqgENLRrvBtnmVODso9V2f83DD0dFZeP7lVaiTtJ8/edit?usp=sharing)

**Comment by AntonMatra** [comment]
[HW8 Anton.pdf](https://github.com/helga-spivak/3008/files/8987385/HW8.Anton.pdf)

**Comment by Polinkarnilova** [comment]
[Карнилова .xlsx](https://github.com/helga-spivak/3008/files/8990259/default.xlsx)

**Comment by ZhNi5** [comment]
Zhiznevskaya


[h_w_8_sql.pdf](https://github.com/helga-spivak/3008/files/8991024/h_w_8_sql.pdf)

**Comment by JuliVoitovich** [comment]
[dz8.xlsx](https://github.com/helga-spivak/3008/files/8991133/dz8.xlsx)

**Comment by ciaonastya** [comment]
[SQL.xlsx](https://github.com/helga-spivak/3008/files/8991268/SQL.xlsx)

**Comment by smalllaliiii** [comment]
[SQL.xlsx](https://github.com/helga-spivak/3008/files/8991680/SQL.xlsx)

**Comment by MariaDanchenko** [comment]
[Маша.xlsx](https://github.com/helga-spivak/3008/files/8991764/default.xlsx)

**Comment by viktoria1807** [comment]
[HW 8.Vika.xlsx](https://github.com/helga-spivak/3008/files/8991766/HW.8.Vika.xlsx)

**Comment by Avaellru** [comment]
[HW8_Dima.docx](https://github.com/helga-spivak/3008/files/8992368/HW8_Dima.docx)

**Comment by PapaKaertoshka** [comment]
Seva
[HW_SQL.docx](https://github.com/helga-spivak/3008/files/8992560/HW_SQL.docx)

**Comment by elenaastreika** [comment]
[HW8.docx](https://github.com/helga-spivak/3008/files/8992871/HW8.docx)

**Comment by skalenchits** [comment]
[домашка_Света.docx](https://github.com/helga-spivak/3008/files/8999309/_.docx)
