### ISSUE TITLE
HW 1 lesson - deadline 04.09.2022 - 15.00

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#16]
Deadline for the homework is Sunday at 15:00 (by Minsk time).
You should write at least 3 User stories :)
Good luck
Additional I've attached file here

Aceptance criteria (критерии приемки):
Для написания используем гугл доки (или аналог) мне скидываем ссылку на файл с возможностью редактировать
Документ должен называться Фамилия_№ ДЗ  
 
[2 урок Домашнее задание.pdf](https://github.com/helga-spivak/3008/files/8827119/2.pdf)

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1UL0Q2G9MU2Xi_9yKaJqjE8khEF81ukJqWKdBifejQuw/edit?usp=sharing

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1N-bZT_4qy5jex8c-j4-yzHE1JOEgkTsfsegns2TPO6A/edit?usp=drivesdk

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1PwQQ88Jglbv8FvzKEkBkDqTwn217Vo6J59J2AM6yNB4/edit?usp=sharing

**Comment by pasha-ivchenko** [comment]
https://docs.google.com/document/d/1MQEZFJ8fu8daAKt1gcHtO-Rr1PMnf7YaIbR6KQUXuT4/edit

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/1cLiOwBh8xh3EtJflJvdPi7mn9qXBX1QDgaiDc3J0tbQ/edit

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1LolWlfqNQ7pasIV3rUXgPMCHl_FEkCnK0vb2TM3GXMQ/edit?usp=sharing

**Comment by Seyurv** [comment]
https://docs.google.com/document/d/1VOhLCv1quB2rFweKyOhyTHVDVDwul8SLPTBEvYGqcYs/edit?usp=drivesdk

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1gptPbmr4cdodUwZOHeiF3DkQSUxiathWnESpISyvfW8/edit

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/e/2PACX-1vRkHZnfcQZvz4xZlzgy4vUGagRT1TQexiiqN68yuBxGP7prmfMAWrVhUTQPdvBf9iiBHEkno5jheMxH/pub

**Comment by zolgag** [comment]
https://docs.google.com/document/d/1za6stWzoDKkAC3mSRvWEoOXQPDpOkreqvY53uNrsfek/edit?usp=sharing

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1ZDIbYkCQqWpW0xSdZHe5WhEUrWSFMA3Vw5MqrlsYdGM/edit

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/160iIjXGUEkExSEQOdSo6yzMsdgoe2iuv7id7jbrWy_M/edit?usp=sharing

**Comment by ekaterinakozhakhmetova** [comment]
https://docs.google.com/document/d/1dyMYBBXjw0m8uB7DZuZ181qPFJ9PklzZyfSxdibZWn4/edit?usp=sharing

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/1Mqd0wuVbTAo2_jQaVIJ6EK-1TsqKKXmwcSCM2NuRacE/edit?usp=sharing

**Comment by helga-spivak** [comment]
Deadline

**Comment by perfilyevstas** [comment]
https://docs.google.com/document/d/1K__I6n--SiZ_wLH2a3EjcAXO0Fo8BT_sD2drahnWOpY/edit?usp=sharing
