### ISSUE TITLE
HW 2 lesson - deadline 11.05.2022 (15.00 UTC+3)

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#18]
Your tasks is attached below
Good luck :)
P.S. You can use Russian for this task

Напоминаю что на занятии мы с вами сделали с 1 по 3 задания 

[Заметки по уроку.pdf](https://github.com/helga-spivak/3008/files/9491681/default.pdf)

Для 4 задания используем сниппет (на видео как его запустить)  или любой другой достпупный метод 

```
 let d = prompt ('Введите дату','');
 let b = new Date(d);
 let date = b.toLocaleString('ru-RU',{ month: 'long', weekday:"long"});
 alert(`это ${date}`)
 console.log(date)
```

https://user-images.githubusercontent.com/57717954/188504046-ccff694e-2c53-4248-abb8-747c4eef9f51.mp4

Для 6 задания используем этот сайт https://r.onliner.by/pk/

Aceptance criteria (критерии приемки):
Для написания используем гугл доки (или аналог) мне скидываем ссылку на файл с возможностью редактировать
Документ должен называться Фамилия_№ ДЗ

[HW_2.pdf](https://github.com/helga-spivak/3008/files/9491086/HW_2.pdf)

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1PFuJt96tr4_-gHS9902o4SNsLXS0zr5ClaokKeHclhc/edit?usp=sharing

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1ttsgmD3881dgVOKFdyQNlINyh4QKi3CFbN8zycCP0Uk/edit?usp=sharing

**Comment by pasha-ivchenko** [comment]
Ivchenko HW_2
https://docs.google.com/document/d/1ja6f2c6QTSGG9pPVrRaBbPfPD_Fux2Z3DutqMBjdUhc/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/36lawnaybxy5i6aboh11y/Haranovich-HW_2.gdoc?dl=0&rlkey=s25pa5jswv7rsqhexs62950df

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/16clk0AtE8UBQYB55S4QFYT20bzGQ7yms8Zuu9mSWyKY/edit

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1g6m1-JZHyJJvghesluwksQrLoNjmeLUHl4y5nj255F8/edit?pli=1
Щекатихина ДЗ № 3

**Comment by zolgag** [comment]
https://docs.google.com/document/d/1tTB6ZrA56KUI3L0hCXx9UJu1YbcQymBMxjuQK2AgylA/edit?usp=sharing

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1pRoz6nWbvJmuprTQfqQRrCtvQB7L_xR2eRiLxguee_k/edit

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1n4aaKqznVZw6dc5r8V6x6JASNZn_ATvDu9btI30bwKU/edit?usp=sharing

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/1CzJrAQ85YmbgI4u_PZD8NDw0KmSLMo2N6f0u6q-N2Rw/edit?usp=sharing

**Comment by perfilyevstas** [comment]
https://docs.google.com/document/d/1vxPwNEcxUKq3_4VjnaGwvvTIvRtexw9t623vOGOPvI0/edit?usp=sharing

**Comment by Seyurv** [comment]
https://docs.google.com/document/d/16u23jj0hy11J5xeUiiBjfy1XtPQUo_Ux9LfpRG4RqF8/edit?usp=sharing

**Comment by ekaterinakozhakhmetova** [comment]
https://docs.google.com/document/d/1_3ILogUMvAsYjw46nbgd3IiHHa_M0WGPXw7Qfh6ZVH0/edit?usp=sharing

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/11_GeyzO7_HoB5CfwavlxobCP_JvjvI9QRMiPjiRcePQ/edit?usp=sharing

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1sQ6X1N7u8BvgIyODI58iL4BF_lMQ8qG4QIuCQchV-34/edit

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/1HwIxDSrQDMcSsTja4E7tL-cvAHgp_cJe1HddCXRnp80/edit?usp=sharing
