### ISSUE TITLE
HW 3 lesson - deadline 18.09.2022 (17.00 Minsk time)

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#19]
Основная домашка - это напистаь тест кейсы (5 штук), чек лист и придумать 3 бага и их описать
Язык выполнения, какой хотите 
Тест-трейл я сделала, на уроке покажу как им пользоваться :) и с учетом этого срок сдачи будет воскременье :) 

`Отчёт о результатах тестирования включает следующие разделы
● Краткое описание. В предельно краткой форме отражает основные достижения, проблемы, выводы и рекомендации. В идеальном случае, прочтения краткого описания может быть достаточно для формирования полноценного представления о происходящем, что избавит от необходимости читать весь отчёт (это важно, т.к. отчёт о результатах тестирования может попадать в руки очень занятым людям).
● Команда тестировщиков. Список участников проектной команды, задействованных в обеспечении качества, с указанием их должностей и ролей в подотчётный период.
● Описание процесса тестирования. Последовательное описание того, какие работы были выполнены за подотчётный период.
● Расписание. Детализированное расписание работы команды тестировщиков и/или личные расписания участников команды.
● Статистика по новым дефектам. Таблица, в которой представлены данные по обнаруженным за подотчётный период дефектам (с классификацией по стадии жизненного цикла и важности).
● Список новых дефектов. Список обнаруженных за подотчётный период дефектов с их краткими описаниями и важностью.
● Статистика по всем дефектам. Таблица, в которой представлены данные по обнаруженным за всё время существования проекта дефектам (с классификацией по стадии жизненного цикла и важности). Как правило, в этот же раздел добавляется график, отражающий такие статистические данные.
● Рекомендации. Обоснованные выводы и рекомендации по принятию тех или иных управленческих решений (изменению тест-плана, запросу или освобождению ресурсов и т.д.) Здесь этой информации можно отвести больше места, чем в кратком описании (summary), сделав акцент именно на том, что и почему рекомендуется сделать в имеющейся ситуации.
● Приложения. Фактические данные (как правило, значения метрик и графическое представление их изменения во времени)
`

Aceptance criteria (критерии приемки):
Для написания используем гугл доки (или аналог) мне скидываем ссылку на файл с возможностью редактировать
Документ должен называться Фамилия_№ ДЗ

[Практикум .pdf](https://github.com/helga-spivak/3008/files/8873189/default.pdf)

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1JgEjCmkMYnjj1ew3VYDzlq97nNcJ_yu0Uy0vsX976Qg/edit?usp=drivesdk

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1Y5fIeyaTOeL3xOhzSwmlxGG56j_SIyTH6TiXwPa32Ak/edit?usp=sharing

**Comment by pasha-ivchenko** [comment]
https://docs.google.com/document/d/1nr21cRX2KIIt4WolZ_yXaJMVcnPq1KR7gNI_d3pll8o/edit?usp=sharing

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/1Sof8MuxeH15KB_WIxJM0aPMvkH1MvLSiXNPoprOoJYU/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/2qbfw5czjprxmyj396mfp/HW-_3.gdoc?dl=0&rlkey=t8llbswycn4i7ewptmhrse5ib

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/13qZs9SSYD7I5O0uCAn5Ed6vt4FsyRJTvQqfx_q9EtPI/edit

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1pRoz6nWbvJmuprTQfqQRrCtvQB7L_xR2eRiLxguee_k/edit#

**Comment by Seyurv** [comment]
https://docs.google.com/document/d/1KemZJUImOWfyLaoH90hXVf3evoVW_N31Qf_ELt5FKuQ/edit?usp=sharing

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1mKuhO2A5tyBAJOR--xEIv0l_BNnkOsuqR2mFE5-y5gY/edit?usp=sharing

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1Ukf34f8vDeU8PYlqJZkZWYWcrMLrCcbeIsRTLq5Azh8/edit?usp=sharing

**Comment by ekaterinakozhakhmetova** [comment]
https://docs.google.com/document/d/17E2NQrNYGugqCXk8jZShYFNY_quzLf00EYITcQjIIX8/edit?usp=sharing

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/1cIWr2KiSAxmfcGIrMPmjVkwr22BobyTTBCfl9AyfxX4/edit?usp=sharing

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1WbMXV_Y7b597NJTJohS8MPvlK_v8ogq66FftefMO4Eg/edit

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1WbMXV_Y7b597NJTJohS8MPvlK_v8ogq66FftefMO4Eg/edit

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1WbMXV_Y7b597NJTJohS8MPvlK_v8ogq66FftefMO4Eg/edit

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1WbMXV_Y7b597NJTJohS8MPvlK_v8ogq66FftefMO4Eg/edit

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1WbMXV_Y7b597NJTJohS8MPvlK_v8ogq66FftefMO4Eg/edit

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/1vTGIg3o-5UoKR6-F05H4om_a8RY8-WtWQutXz0I0rPU/edit?usp=sharing
