### ISSUE TITLE
HW 6 lesson - deadline 30.09

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#21]
https://testbase.atlassian.net/wiki/home (логин — [mail.for.testbase@gmail.com](mailto:mail.for.testbase@gmail.com); пароль — 12345678910) тут лежит документация по апишке и описание методов

https://www.chaijs.com/api/bdd/ тут можете почитать про то как писать тесты, в котоых есть expect 

Ваше ДЗ:

1. Сделать запросы createuser, doregister and delete avatar в формате удобном вам
2. Попытаться протестировать эти методы, пользуясь входными данными из этого документа, прибегая к анализу и различным техникам тест-дизайна. (Проверок делаете, сколько считаете нужным) Например, попробовать отправить запрос без параметра, обязательного для заполнения. Кто чувствует в себе силы и мощь, может тесты автоматизировать
Не более 3 проверок из пункта 2 оформить в отдельном документе со скриншотами и пояснениями, что именно проверяли.
А также поделиться коллекциями ваших запросов. Не забываем их сохранять после работы.
ссылка на коллекцию, что мы делали на уроке: https://www.getpostman.com/collections/558ca267cda43e1c44b4
ссылка 2, где все работает (magic): https://www.getpostman.com/collections/e4f771fbf7dc5bed1a52

[Практикум(7).pdf](https://github.com/helga-spivak/3008/files/8943257/7.pdf)

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/1Lzf5IqVwoNfg65ylHNiFmik4bKVd122wwXXeKgaAKnw/edit

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1LFvpEy_U4V52q853hyjlb_YF_jR9qG_QkNfjoSFq2rQ/edit?usp=sharing

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1HMEww10wXZkjjROaWiUTSMM_wmsyeteZH5if5N9yULY/edit

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/1Jf0jp986_Y9rD4kATY2hYSSADkuVCrfgsHYrbZ6BQLM/edit?usp=sharing

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1lGG7rgyyqlAgng_lKGojocKzIqm-H_VmzK5Ju9wUswc/edit?usp=sharing

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/17cIJMP5lVSGho0QTVTEtms2XWHK-zJ_hTEVB6Q2BhkY/edit

**Comment by pasha-ivchenko** [comment]
Ivchenko HW 6
https://www.getpostman.com/collections/0b85f4dfd2f8ae4d4804

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/1GGxcNCXLGXgOhjIunpNnrsHm2-CEHWPOE8gxDYzto5o/edit?usp=sharing

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1C55_fEyj9osWEkCXZXzLqu_QySTuHlk1JAejqWfJU6Y/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/3whm2jn6mnt4b4fzjtjha/HW-6-lesson-deadline-30.09.gdoc?dl=0&rlkey=fzykarncxg68khl8xdswszoj5

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/1d5vP3fe1dCvJUwkuX0j0q-00k38ITyqBDAZo96vbmUY/edit?usp=sharing

**Comment by KSaiko2007** [comment]
https://www.getpostman.com/collections/ee1e9d627ac5ebc9f3b3

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1g-Rsy2KMz_mQmohbkuaMQyJc3xfkaBAgQZctHFU5Cgo/edit

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1g-Rsy2KMz_mQmohbkuaMQyJc3xfkaBAgQZctHFU5Cgo/edit
