### ISSUE TITLE
HW lesson 7 deadline 28.09

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#22]
Вашей домашкой бдет сделать задачи:  17, 18, 19, 21, 22 (https://www.sql-ex.ru/) - мне скринуть скрины (оформить в один документ) такого плана (видно номер задачи, ваш код и что запрос верный)
Щфщрмляем все в гугл доках 

![Image](https://user-images.githubusercontent.com/57717954/192359642-890f5646-8251-4ff3-98df-907c1d4d10e8.png)

https://www.w3schools.com/sql/default.asp - тут почитать и выучить все что проходили на уроке:

SQL SELECT DISTINCT,
SQL WHERE
SQL AND, OR and NOT Operators
SQL ORDER BY
SQL INSERT INTO
SQL UPDATE
SQL DELETE
SQL TOP, LIMIT, FETCH FIRST or ROWNUM
SQL MIN() and MAX()
SQL COUNT(), AVG() and SUM()
SQL LIKE
SQL IN
SQL BETWEEN

Решение задач, пройденных на уроке
1.select model, speed, hd размер from PC
where price < 500

2.select DISTINCT maker from product
where type = 'printer'

3.select model, ram, screen from Laptop
where price > 1000

4.select * from Printer 
where color = 'y'

5.select model, speed, hd from PC
where cd in ('12x', '24x') and price < 600

10.select model, price from Printer
where price = (select max (price) from Printer)

11.select avg(speed) as speed from PC

12.select avg (speed) speed  from laptop
where price > 1000

13.select avg (speed) as speed from PC 
where model in (select model from product where maker = 'A')

15.select hd from pc
group by hd
having count(model) > 1

16.select distinct B.model as test1, A.model as test, A.speed, A.ram
from PC as A, PC as B
where B.speed = A.speed and B.ram = A.ram and A.model < B.model

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1h1KU3nwF5ENZugbMNLhFtGRscdE39chxaI_3ZdJr7Ac/edit

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/12sQhNwKbncbjmEdgNEVk07qcCmC2vn9HJyKtwEZ0N_0/edit?usp=sharing

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1T_M3TTfoYHzGJMk7oR2c45VPUDMgyrkvhRcF02kXzxU/edit

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1uCs-PA_HG2kyFez_AW529x6Mwi6Ty8OVUV5MT20EB78/edit?usp=sharing

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1yIu2eVeDr6NMpg6aL9ZejE5Dh2brd3pRIO92q-B63Bs/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/z7k6kscjeo53e1bx86znr/HW-lesson-7-deadline-28.09.gdoc?dl=0&rlkey=b5lao1fnwljllq6d7ingtmgp9

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1sGy2YfBRiF6I7VMdT7Ez87-4Gc0JEypCU5Z-11gpGU8/edit

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/1R4Ax3B1SVcel6T81sfwwlM5Xg1OT1pmBzIOTkXTIwDQ/edit?usp=sharing

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/1kGvqJp580V_2DnhjLZ77ITwGR45YYJhZC49RRcg9UKU/edit

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1Roq9fNa27hKJSgbRf13gcnsy9edwBabQQEsQ79Fc4MU/edit

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/141kxDAfgY_uzqMOSciVyuPgY51yODWWU5BeUjiHfoIQ/edit?usp=sharing
