### ISSUE TITLE
Курсовая работа deadline 10.10.2022 (дата не фиксированная)

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#23]
https://betacode.net/10713/install-postgresql-database-on-windows#a114891 тут вам помощь по созданию БД и таблиц

[Курсовая работа.pdf](https://github.com/helga-spivak/3008/files/9041730/default.pdf)

**Comment by samiaasv** [comment]
1.1. Структура модулей teachmeskills.by https://www.gloomaps.com/yJ7eAjt3yX
1.2-1.4 чек-лист, тест-кейсы, баг-репорты  https://docs.google.com/document/d/1c4r8-_1-QkVrb7yrh8DPNNLdBxfMNvXundi0t8B8IYY/edit

2. API testing: https://docs.google.com/document/d/1xTwc6uW5tyUPZk41HLagJjA82DhtG5eL3mCYXXP__cM/edit

3. PostgreSQL https://docs.google.com/document/d/1gobLrbuPbAy1GmfAfzFTrlxngvKMx1P2Trhx3FkiuLc/edit

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1hEuxRzStT9iw9XBFE7meagOBCytRVqwq9ccJXnHN3sw/edit?usp=sharing

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1Y-imF6EXfiJJVE-DV_6Pz7he2Jh-0fO-Qea3CIhyPEU/edit
https://docs.google.com/document/d/1chtCrhP_bsfmiW4HB93JGxaEHD7_x7sTUp3HTPQQdb0/edit

**Comment by serzhagolkin** [comment]
WEB & API testing: https://docs.google.com/document/d/1ecgFiHaKt91ebt96sW8T5TpSkTzOXE0d649XTyRO-Ro/edit?usp=sharing
SQL testing: https://docs.google.com/document/d/1H3Rvzf1ncLIyd9bvlFzgPpxIxLwQOQNabcbLtyLWIsY/edit?usp=sharing

**Comment by vikabraim** [comment]
https://docs.google.com/spreadsheets/d/1B32dH9gYmpcEMh-sYwUSxBovCIV_cVcN6_gCy6smGkE/edit?usp=sharing

**Comment by pasha-ivchenko** [comment]
https://docs.google.com/document/d/1wQvBdemWstH8LspnQN0DS6ZP2RxC8gfhzB4xXCC0Exg/edit?usp=sharing

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1pWwzJcZ3tA11nw2GOIxveeghdzjrZrPdC8ZnVwy1ZXw/edit?usp=sharing

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1cWmke1niwhdqKM1s84ELNcVyBF5pvPkGt9hZjzh4KE8/edit

**Comment by juliamartsul** [comment]
Тестирование сайта https://docs.google.com/document/d/1chdX1F_WeIoBnWcdL9YwTUBwjs4Cq0lc5YrWblHOb80/edit?usp=sharing

API тестирование https://docs.google.com/document/d/1ZrzhbHvCtRAD4nlm8HMmyi6vt83HDoBaB6jj3lAo-GI/edit?usp=sharing

SQL https://docs.google.com/document/d/1oLz0W3HyYNTIeEXmEWG4QTmKoi1UM_NvQJWw0UThXmw/edit?usp=sharing

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/1fwuWH3y3PNbNecEXFVEm88f0aZU4O5EDoLGDp9Nyik4/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/9lgtgvjeulvo67pvr598f/.gdoc?dl=0&rlkey=r94mp08dmdhv5blj7vnsyaswa

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1pJKTG6i1G8JFFABH4L1m2cNmz9CyG9uSO0sLAzIMp-o/edit
