### ISSUE TITLE
HW lesson 9 - SQL deadline 09.09.2022 (12.00 Minsk time)

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#24]
Вам необходимо сделать запросы тут: https://livesql.oracle.com/
Запросы оформляем в документ, чтобы я могла их все выполнить у себя :) 
Файл с заданием на диске https://disk.yandex.by/d/9YapkjUaCW4VFg  :) 

пример запроса (2 задание) (помним про  hr.)
select * from hr.employees where DEPARTMENT_ID = 100

Aceptance criteria (критерии приемки):
Для написания используем гугл доки (или аналог) мне скидываем ссылку на файл с возможностью редактировать
Документ должен называться Фамилия_№ ДЗ

https://user-images.githubusercontent.com/57717954/176049966-dfbfda23-91a6-4a33-a42d-aa44b37b9305.png

Примеры с урока (case я починила, проблема была в лишних кавычках после end as) :
/*select * from  HR.COUNTRIES
where REGION_ID != 2 */

select * from  HR.EMPLOYEES
where DEPARTMENT_ID = 100

select  EMPLOYEE_ID, FIRST_NAME,SALARY, DEPARTMENT_ID, 
case  
    when DEPARTMENT_ID =10 then 'cats' 
    when DEPARTMENT_ID =30 then 'dogs' 
    when DEPARTMENT_ID =50 then 'bugs' 
    else 'smth' 
end as animals 
from HR.EMPLOYEES 
where DEPARTMENT_ID in (10, 30, 50)

select distinct emp.SALARY
from HR.EMPLOYEES emp
where emp.JOB_ID like 'IT%'

select distinct emp.SALARY
from HR.EMPLOYEES emp
join hr.DEPARTMENTS dep on dep.DEPARTMENT_ID = emp.DEPARTMENT_ID
where dep.DEPARTMENT_name = 'IT'

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/18MOYybVv32OoYNAyWlwOtn_DNaD051y-Zj1_n89RcyM/edit?usp=drivesdk

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/15lCsBHnzAL07eDlpvsmFCcwAEbb-yJDy4OoV3B7llzo/edit

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1ofExet6I_m5sIcOaJbAP_CiDIueQOmmLEZ5E0xgqtXc/edit?usp=sharing

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1nu7of8b9zySeYuMFNd4Jnr9ZZlz_bxAL40A6li4OmY8/edit?usp=sharing

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/1KCiS-GNTlGXidPKzvcb_sM7KXfs-pdD_dG-JBvBvUuo/edit?usp=sharing

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1hmk2M_qGmzENcE4BMHWCf6BhfeRKPpRMioy6xZXRq7I/edit

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/1LrmR2OVfzW5Cu9VQpAL-j7F8vzU_wBkIoMZIxCOrJDA/edit?usp=sharing

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/13EDCwiAJPnKh3dfUDknaV2RuG-i5y1BYY9i3ZptYvYg/edit?usp=sharing

**Comment by pasha-ivchenko** [comment]
https://docs.google.com/document/d/1OQzfiRe4BgW3HrdFm8qhJqP9zjZGUBRBWCOAbCPck9w/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/7nutxavukbwh8vi936iv8/HW-lesson-9-SQL.gdoc?dl=0&rlkey=7dczl1nq5tb3n25yvvdawa1k4

**Comment by TinaSergey** [comment]
https://docs.google.com/document/d/1obd9ROdIEkzgF80tkQwWwqsn-sR0QpAHtfMXKg3JQLk/edit?usp=sharing

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/14PKHiGxON-CaSet9i1_mg95XHu3cIEfHL2D-0GUxSlY/edit
