### ISSUE TITLE
HW lesson 9 - site deadline 06.10.2022

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#25]
Смотрим презентацию и определяем типы версток, делаем скриншоты и присылаем мне 

Aceptance criteria (критерии приемки):
Для написания используем гугл доки (или аналог) мне скидываем ссылку на файл с возможностью редактировать
Документ должен называться Фамилия_№ ДЗ

**Comment by pasha-ivchenko** [comment]
https://docs.google.com/document/d/1d4q6ig9YpbIITLxOEiogICd_UO0J2oPyKwcoRBs2YGk/edit?usp=sharing

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/12HCSG70kx89tb_noWEUiSKILny8AjmQwPQ5p5vheDpg/edit?usp=sharing

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1-p3UCU4cR6cfoWPc52ISh9Qf6ryRPEr-Wl1Cak0bQY4/edit?usp=sharing

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1xpkC-i8Yk7YOgZMdzCcwXVagDkNA-kQMdzm2K4RiuQI/edit

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1FnJpaqcnLs8_YHSTe8ITN2ftvBdyNgOA_24siakQQKQ/edit

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/1qlmxgM1elIViebB8znE9mGYhU1mhi3pZQyOz5-Tfcdk/edit?usp=sharing

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/1T_jslGDJotGbv35FgZpwXW-IjUTKGVS5EVvmh--hF_Q/edit

**Comment by juliamartsul** [comment]
https://docs.google.com/document/d/1Gxn4Uf6k3ytDk1-DRyqI6VIPJnfNSwFb1tSs2lvaJ3Q/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/mpucd9lxvuu8jchqiyznh/HW-lesson-9-site-deadline-06.10.2022.gdoc?dl=0&rlkey=kcnrpqj7p6cyf3vv64u5llrej

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1EzmIJQyPbM3x-oQz_10KnW2Luwki-48W7PZzKuWZscU/edit?usp=sharing

**Comment by KSaiko2007** [comment]
https://docs.google.com/document/d/1-lnew4wOkLQNRL1TFkmmzvK966jVe0dtd0fuhuwyuuQ/edit
