### ISSUE TITLE
HW 10 lesson- deadline 12.10.2022

### ISSUE THREAD

**Issue by helga-spivak** [helga-spivak/3008#26]
Вот что вам надо будет сделать:
Предусловие

https://testbase.atlassian.net/wiki/spaces/SHOP/overview?homepageId=1411056054 - как доп материал потыкать АПИ

зарегистрироваться тут https://university.blazemeter.com/dashboard
найти курс JMeter™ Intro и посмотреть как утсановить JMeter (это уроки 2-3, но можете посмотреть первый блок)
к тикету приаттачена папка с примером что мы сделали на уроке
https://www.w3schools.com/whatis/whatis_cli.asp тут команды для работы с командной строкой

1. Записать при помощи Jmeter сценарий для сайта http://litecart.stqa.ru/, состоящий из запросов к трем страницам:
открытие главной страницы,
открытие страницы категории товаров
открытие страницы отдельного товара
2. Написать тест кейсы (3 шт) для следующего функционала:
поиск необходимого товара (подумать, какие есть способы найти товар из разных мест приложения)
добавление товара из различных мест приложения
кейсы, покрывающие сортировку товаров и их фильтрацию
набросать юзабилити чек лист (скорость, ориентация,удобство, логичность и т.д.)
протестировать авторизацию с последующей чисткой куки
протестировать добавление товара с последующей чисткой кэша, мониторинг Network in devtools
протестировать поле “Поиск товара”
протестировать приложение на локализацию со сменой страны и языка
протестировать приложение при успешном соединении к интернету, со слабым сигналом интернета и его
отсутствием

**Comment by samiaasv** [comment]
https://docs.google.com/document/d/1r712T8HPYgAFOObUJTasKPYALwJdW2IjR2675M4FofI/edit

**Comment by riabitsanatallia** [comment]
https://docs.google.com/document/d/1bqxj53xje2mcBYOWPkdFXvr3Ox8q6H8wiSkGMgRs6cU/edit?usp=sharing

**Comment by vikabraim** [comment]
https://docs.google.com/document/d/1yYLP-6Hpp7x6aa0c4Aa8KVFxm2xfmyg_UXsJ9M5OTTk/edit?usp=sharing
jmeter https://docs.google.com/document/d/13Wz-v2IdsRSNuf6mnKaSTmuWCxCHjs5yLVYO1ge6pME/edit?usp=sharing

**Comment by AnnaShchakatsikhina** [comment]
https://docs.google.com/document/d/1td9Q4NbyKSuweOD2-I1kfhClpKA2mG9RBN_eYSCP_LA/edit?usp=sharing

**Comment by nasxxt** [comment]
https://www.dropbox.com/scl/fi/j12c8attlq1b57gh5ib41/HW-10-lesson.gdoc?dl=0&rlkey=bo7ggf3a6ikhlslf2h6c2mkb7

**Comment by ordsveta** [comment]
https://docs.google.com/document/d/1sLYtinHrS5NtgfdfZ27X4WgEnv_Dvdfd6zsHMoD3tHk/edit#

**Comment by pasha-ivchenko** [comment]
https://docs.google.com/document/d/19ah2EY2Fjuvtr25swexV1cCD9a0zGLFhQcZTZ_H2-ZU/edit?usp=sharing

**Comment by angelinadobr** [comment]
https://docs.google.com/document/d/19CAEoktcIbk3mgbjHh9b4DZkB-XJiHTwboRfvZ4_jKI/edit?usp=sharing

**Comment by serzhagolkin** [comment]
https://docs.google.com/document/d/1jcX3grmvgLj1gHKQYTtFeejedQBSm8CDVtrl_nGuO5U/edit?usp=sharing

**Comment by juliamartsul** [comment]
Jmeter https://drive.google.com/file/d/18mYjoUrFksR4kRrUWcmZUIADbBuOxgLJ/view?usp=sharing

Тест-кейсы https://docs.google.com/document/d/1Qn_zPSDmh5r2BydXQRuagFXyYF8sSh0muVjsucyZ8PQ/edit?usp=sharing
